console.log("my first console project");
var firstname="ranbeer";
var lastname="kapoor";
var fullname= firstname.concat(lastname);
console.log (fullname);
var a=10;
var b=5;
var add=a+b;
console.log (add);
var sub=a-b;
console.log (sub);
var multiple=a*b;
console.log(multiple);
var division=a/b;
console.log (division);